_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 7b0e3e49-0bea-45d9-b97b-270c088e29f4
name: 'Innoraft Click'
mail: admin@example.com
slogan: ''
page:
  403: /node/12
  404: /node/11
  front: /node/13
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
